-- MySQL Script generated by MySQL Workbench
-- lun 06 nov 2023 15:47:40
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema productosdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema productosdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `productosdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `productosdb` ;

-- -----------------------------------------------------
-- Table `productosdb`.`tbProducts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `productosdb`.`tbProducts` (
  `idProducto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  `brand` VARCHAR(120) NOT NULL,
  `price` INT NOT NULL,
  `category` VARCHAR(120) NOT NULL,
  `stock` INT NOT NULL,
  PRIMARY KEY (`idProducto`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
